# Bitbucket pipelines configuration to run the tox tests
# (See https://confluence.atlassian.com/x/VYk8Lw)
image: ubuntu:16.04

pipelines:
  default:
    - step:
        script:
            - apt-get update
            - apt-get install -y apt-utils software-properties-common
            - add-apt-repository ppa:fkrull/deadsnakes
            - apt-get update
            - apt-get install -y python python2.7 python3.2 python3.3 python3.4 python3.5 python3.6 python3.7 virtualenv
            - virtualenv /opt/venv
            - /opt/venv/bin/pip install tox
            - /opt/venv/bin/tox
